// Default paths to TeX binaries, for TeXworks
// Generated by /home/atsuhito/misc/pack/TeXworks/texworks-0.5~svn1363/getDefaultBinPaths.sh
#define DEFAULT_BIN_PATHS "/usr/local/texlive/2013/bin/x86_64-linux:/usr/local/texlive/2012/bin/x86_64-linux:/usr/local/texlive/2011/bin/x86_64-linux:/usr/local/texlive/2010/bin/x86_64-linux:/usr/local/texlive/2009/bin/x86_64-linux:/usr/local/texlive/2008/bin/x86_64-linux:/usr/local/texlive/2007/bin/x86_64-linux:/usr/local/bin:/usr/bin"
