// Default paths to TeX binaries, for TeXworks
// Generated by /home/norbert/Development/TeX/debian/git/TeXWorks/texworks-upstream.git/getDefaultBinPaths.sh
#define DEFAULT_BIN_PATHS "/usr/local/texlive/2017/bin/x86_64-linux:/usr/local/texlive/2016/bin/x86_64-linux:/usr/local/texlive/2015/bin/x86_64-linux:/usr/local/texlive/2014/bin/x86_64-linux:/usr/local/texlive/2013/bin/x86_64-linux:/usr/local/texlive/2012/bin/x86_64-linux:/usr/local/texlive/2011/bin/x86_64-linux:/usr/local/texlive/2010/bin/x86_64-linux:/usr/local/bin:/usr/bin"
